### ISSUE TITLE
'Vehicle' name change

### ISSUE THREAD

**Issue by samankim** [tawheeler/AutomotiveDrivingModels.jl#20]
Since the Vehicle type is used to represent pedestrian models as well, I suggest changing the names with 'Vehicle' to Agent (i.e. Vehicle --> Agent, VehicleDef --> AgentDef, VehicleState --> AgentState).

**Comment by MaximeBouton** [comment]
I think this is a reasonable. We mentioned using the word 'Entity' as well but it is a bit more vague.

**Comment by MaximeBouton** [comment]
Now everything is called `Entity`
