### ISSUE TITLE
What are the units of 'longitude accelerate' and 'turning_rate values'? 

### ISSUE THREAD

**Issue by HighlyAuditory** [tawheeler/AutomotiveDrivingModels.jl#22]
What are the units of 'longitude accelerate' and 'turning_rate values' that the simulator receive?
For the second one, should the turn rate be global or ego?

**Comment by MaximeBouton** [comment]
Are you referring to the `AccelTurnRate` action type? 
If yes, I believe they are in SI units so m/s^2  for the longitudinal acceleration and rad/s for the turn rate. 
You can see the source code of the associated `propagate` method here:
https://github.com/sisl/AutomotiveDrivingModels.jl/blob/master/src/2d/actions/accel_turnrate.jl

The ego vehicle in the global frame is represented by (x,y,\theta, v), the turn rate is the derivative of \theta.
