### ISSUE TITLE
proposed name change

### ISSUE THREAD

**Issue by tawheeler** [tawheeler/AutomotiveDrivingModels.jl#3]
This package has a long name.
I propose changing it to `Automotive`
Other options are:

- `Auto`
- `AutoCore` - as the other packages are called Auto\<Something\>
- `AutoSim`

**Comment by MaximeBouton** [comment]
`AutomotiveSimulators.jl` might be a good name!

We might want to rename `AutoViz.jl` to `AutomotiveVisualization.jl` for consistency...

**Comment by MaximeBouton** [comment]
https://github.com/sisl/AutomotiveSimulator.jl
