### ISSUE TITLE
`observe!` default is too specific

### ISSUE THREAD

**Issue by MaximeBouton** [tawheeler/AutomotiveDrivingModels.jl#38]
I don't think we should provide a default for the `observe!` method and let it throw a method error when it is not implemented for a custom model. 

https://github.com/sisl/AutomotiveDrivingModels.jl/blob/master/src/behaviors/interface.jl#L41

@mattuntergassmair

**Comment by mattuntergassmair** [comment]
Agreed, the current implementation was silently skipping the `observe!` function call and it was difficult for me to figure out I had not implemented that function for my specific types
