### ISSUE TITLE
The sisl/AutomotiveDrivingModels.jl doesn't contain any definition to type IntegratedContinuous 

### ISSUE THREAD

**Issue by gdpinchina** [tawheeler/AutomotiveDrivingModels.jl#5]
Hi, I've download sisl/latent_driver and try running through it. Type `IntegratedContinuous` has been used in several files in `sisl/lantent_driver`. Such as:
`sisl/latentdriver/pull_traces/passive_aggressive.jl    row:89
sisl/latentdriver/pull_traces/pull_2d_traces_passive_aggressive.jl    row:59
sisl/latentdriver/validation/AutoViz.jl    row25
...`
I can't find this type's definition in `sisl/AutomotiveDrivingModels.jl`. But I can find the definition in `maxiaoba/LofiSimu/AutomotiveDrivingModels.jl`. I have searched the whole github with the key word: `IntegratedContinuous` and I found that only the latter contains a definition to `IntegratedContinuous`. And the latter seem raise much less concern in github. Now that these two repositories are in a same 
organization, why the  `sisl/AutomotiveDrivingModels.jl` cannot support `sisl/lantent_driver`.
Thank you for your time and best wishes.

**Comment by tawheeler** [comment]
AutomotiveDrivingModels is constantly being improved. We recently underwent a big change where we overhauled the type system. You can checkout the ITSC2016 branch which should have what you need.

**Comment by gdpinchina** [comment]
Thanks a lot. But ITSC2016 branch still doesn't work. I use maxiaoba/LofiSimu/AutomotiveDrivingModels.jl instead.
