### ISSUE TITLE
Tim2DDriver relies on QueueRecord

### ISSUE THREAD

**Issue by mattuntergassmair** [tawheeler/AutomotiveDrivingModels.jl#62]
`Tim2DDriver` makes use of `QueueRecord` structure for scenes
see `tim_2d_driver.jl`, line 47

This makes it incompatible with the new simulation interface

**Comment by MaximeBouton** [comment]
It is using the feature extraction mechanism which needs to be passed a `QueueRecord`. 
https://github.com/sisl/AutomotiveDrivingModels.jl/blob/master/src/behaviors/tim_2d_driver.jl#L53

I think the feature extraction needs to be re-designed but this is for another issue. 

If one wants to remove the use of `QueueRecord` for the Tim2Ddriver I think it is a matter of replacing line 53 by `velf(scene[vehicle_index]).t` (verify the implementation of the `VELFT` feature extractor)

**Comment by mattuntergassmair** [comment]
Ok, this should be partially fixed in #64 but required some changes in Tim2DDriver and MOBIL. A clean solution would require a major overhaul of feature-extractors
