### ISSUE TITLE
Get rid of documentation warnings - make documentation work for interfaces

### ISSUE THREAD

**Issue by mattuntergassmair** [tawheeler/AutomotiveDrivingModels.jl#63]
Using `julia --project make.jl` prints several warnings for missing docstrings, for example for the `get_name` function. `get_name` is documented in the interface, but without argument signature. The documentation (such as in `docs/src/behaviors.md`) currently lists `get_name(::DriverModel` for documentation which creates a warning.

More generally, the goal should be to make the documentation-generation warning-free

**Comment by MaximeBouton** [comment]
I agree with this. 

Regarding `get_name` specifically, it should be deprecated now so we can remove it from the doc.
