### ISSUE TITLE
How to add a new car-following model?

### ISSUE THREAD

**Issue by durraniu** [tawheeler/AutomotiveDrivingModels.jl#81]
Thank you for creating this package. I am new to julia and just stumbled upon this awesome package. 

I can see in the documentation that a few car-following models e.g., IDM is included. Can I contribute by adding more models, e.g., Wiedemann car-following model? I can't seem to find the documentation where I can contribute.

Thanks!

**Comment by MaximeBouton** [comment]
Hello! Thank you for your interest you are very welcome to contribute a new driver model. I am not familiar with the one you mention, maybe link to a paper. 

Check this example:
https://sisl.github.io/AutomotiveDrivingModels.jl/latest/examples/crosswalk/#Simulate-the-scenario-1

The full list of methods for driver model is listed here: https://sisl.github.io/AutomotiveDrivingModels.jl/latest/behaviors/#Interface-1  

You can also look at the driver models that are implemented in here for more complex examples https://github.com/sisl/AutomotiveDrivingModels.jl/tree/master/src/behaviors 

Feel free to submit a pull request

**Comment by durraniu** [comment]
Thank you. I'll look into these resources.
